import os
import git
import json
from github import Github, Auth
from dotenv import load_dotenv
from groq import Groq
from datetime import datetime

load_dotenv()

client = Groq(api_key=os.getenv("GROQ_API_KEY"))

def get_github_client():
    token = os.getenv("GITHUB_TOKEN")
    if not token:
        print("No GitHub token found in .env file.")
        print("Add GITHUB_TOKEN=your-token to .env")
        print("Get token at: github.com/settings/tokens")
        return None
    auth = Auth.Token(token)
    return Github(auth=auth)

def list_repos():
    g = get_github_client()
    if not g:
        return []
    user = g.get_user()
    repos = list(user.get_repos())
    print(f"\nYour GitHub repos ({len(repos)} total):")
    for i, repo in enumerate(repos):
        print(f"  {i+1}. {repo.name} — {repo.description or 'no description'}")
    return repos

def get_repo_files(repo_name: str):
    g = get_github_client()
    if not g:
        return []
    user = g.get_user()
    repo = g.get_repo(f"{user.login}/{repo_name}")
    contents = repo.get_contents("")
    files = []
    while contents:
        file = contents.pop(0)
        if file.type == "dir":
            contents.extend(repo.get_contents(file.path))
        else:
            files.append(file.path)
    print(f"\nFiles in {repo_name}:")
    for f in files:
        print(f"  {f}")
    return files

def get_file_content(repo_name: str, file_path: str):
    g = get_github_client()
    if not g:
        return None
    user = g.get_user()
    repo = g.get_repo(f"{user.login}/{repo_name}")
    file = repo.get_contents(file_path)
    content = file.decoded_content.decode("utf-8")
    return content

def analyze_repo_for_bugs(repo_name: str):
    g = get_github_client()
    if not g:
        return
    user = g.get_user()
    repo = g.get_repo(f"{user.login}/{repo_name}")

    code_extensions = [".py", ".js", ".java", ".cpp", ".ts", ".go", ".rs"]
    contents = repo.get_contents("")
    files = []

    while contents:
        file = contents.pop(0)
        if file.type == "dir":
            contents.extend(repo.get_contents(file.path))
        elif any(file.path.endswith(ext) for ext in code_extensions):
            files.append(file)

    print(f"\nAnalyzing {len(files)} code files in {repo_name}...")
    all_bugs = []

    for file in files[:5]:
        print(f"  Checking {file.path}...")
        try:
            content = file.decoded_content.decode("utf-8")
            if len(content) > 100:
                prompt = f"""Analyze this code for bugs. File: {file.path}

Code:
{content[:2000]}

Return ONLY a JSON object:
{{
    "file": "{file.path}",
    "bugs": [
        {{
            "line": <number>,
            "type": "<error type>",
            "description": "<what is wrong>",
            "severity": "<high, medium, or low>"
        }}
    ]
}}

Return ONLY the JSON. No extra text."""

                response = client.chat.completions.create(
                    model="llama-3.3-70b-versatile",
                    messages=[{"role": "user", "content": prompt}]
                )

                raw = response.choices[0].message.content.strip()
                if raw.startswith("```"):
                    raw = raw.split("```")[1]
                    if raw.startswith("json"):
                        raw = raw[4:]
                raw = raw.strip()

                try:
                    result = json.loads(raw)
                    if result["bugs"]:
                        all_bugs.append(result)
                        print(f"    Found {len(result['bugs'])} bugs")
                    else:
                        print(f"    No bugs found")
                except:
                    pass
        except:
            pass

    print(f"\nTotal files with bugs: {len(all_bugs)}")
    for file_result in all_bugs:
        print(f"\n{file_result['file']}:")
        for bug in file_result["bugs"]:
            print(f"  Line {bug['line']} — {bug['type']} ({bug['severity']})")
            print(f"  {bug['description']}")

    return all_bugs

def create_issue_for_bug(repo_name: str, bug: dict, file_path: str):
    g = get_github_client()
    if not g:
        return
    user = g.get_user()
    repo = g.get_repo(f"{user.login}/{repo_name}")

    title = f"Bug: {bug['type']} in {file_path} at line {bug['line']}"
    body = f"""## Bug Report — Auto-generated by AI SWE Bot

**File:** {file_path}
**Line:** {bug['line']}
**Type:** {bug['type']}
**Severity:** {bug['severity']}

## Description
{bug['description']}

## Steps to Fix
This bug was automatically detected by AI SWE Bot.
Run the auto-fix feature to resolve this issue.

---
*Generated on {datetime.now().strftime('%Y-%m-%d %H:%M')}*"""

    issue = repo.create_issue(title=title, body=body)
    print(f"Issue created: {issue.html_url}")
    return issue

def commit_fixed_code(repo_path: str, file_path: str, fixed_content: str, bug_description: str):
    try:
        repo = git.Repo(repo_path)
        full_path = os.path.join(repo_path, file_path)

        with open(full_path, 'w', encoding='utf-8') as f:
            f.write(fixed_content)

        repo.index.add([file_path])
        commit_message = f"fix: {bug_description[:50]} — Auto-fixed by AI SWE Bot"
        repo.index.commit(commit_message)
        print(f"Committed: {commit_message}")

        origin = repo.remote(name='origin')
        origin.push()
        print("Pushed to GitHub successfully.")
        return True
    except Exception as e:
        print(f"Git error: {e}")
        return False

def get_pull_requests(repo_name: str):
    g = get_github_client()
    if not g:
        return []
    user = g.get_user()
    repo = g.get_repo(f"{user.login}/{repo_name}")
    prs = list(repo.get_pulls(state='open'))
    print(f"\nOpen pull requests in {repo_name}: {len(prs)}")
    for pr in prs:
        print(f"  #{pr.number} — {pr.title}")
    return prs

def init_local_repo(folder_path: str, repo_name: str):
    g = get_github_client()
    if not g:
        return

    user = g.get_user()
    print(f"Creating GitHub repo: {repo_name}")
    repo = user.create_repo(
        repo_name,
        description="Created by AI SWE Bot",
        private=False
    )

    local_repo = git.Repo.init(folder_path)
    with open(os.path.join(folder_path, "README.md"), 'w') as f:
        f.write(f"# {repo_name}\n\nCreated by AI SWE Bot")

    local_repo.index.add(["README.md"])
    local_repo.index.commit("Initial commit — AI SWE Bot")
    local_repo.create_remote("origin", repo.clone_url)
    local_repo.remotes.origin.push(refspec="master:master")
    print(f"Repo created and pushed: {repo.html_url}")
    return repo

if __name__ == "__main__":
    print("=" * 40)
    print("  GitHub Integration Test")
    print("=" * 40)
    print()

    token = os.getenv("GITHUB_TOKEN")
    if not token:
        print("No token found. Please add GITHUB_TOKEN to .env and run again.")
        print("Get token at: github.com/settings/tokens")
        print("Select: repo and issues permissions")
    else:
        print("Token found. Listing your repos...")
        repos = list_repos()
        if repos:
            print("\nGitHub integration is working!")
            print(f"\nYou can now:")
            print("  analyze_repo_for_bugs('repo-name') — scan any repo for bugs")
            print("  create_issue_for_bug(...) — auto-create GitHub issues")
            print("  commit_fixed_code(...) — auto-commit and push fixes")
            print("  get_pull_requests('repo-name') — list open PRs")
        else:
            print("\nConnected to GitHub but no repos found.")
            print("Create a repo at github.com and run again.")
